# DN_SuperBook_PDF_Converter - Taskfile
# https://taskfile.dev/
#
# Usage:
#   task --list        # Show all tasks
#   task setup         # Initial setup (NVIDIA Container Toolkit)
#   task build         # Build container
#   task convert       # Run PDF conversion
#   task shell         # Interactive shell

version: "3"

vars:
  IMAGE_NAME: superbook-pdf-converter
  IMAGE_TAG: latest
  INPUT_DIR: ./examples/00_before
  OUTPUT_DIR: ./examples/02_after

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ===========================================
  # Setup Tasks
  # ===========================================

  setup:
    desc: Setup NVIDIA Container Toolkit for Podman (requires sudo)
    cmds:
      - echo "Setting up NVIDIA Container Toolkit..."
      - |
        if command -v nvidia-ctk &> /dev/null; then
          echo "nvidia-ctk is already installed"
        else
          echo "Installing NVIDIA Container Toolkit..."
          curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
          curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
            sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
            sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
          sudo apt-get update
          sudo apt-get install -y nvidia-container-toolkit
        fi
      - sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml
      - echo "Setup complete! Run 'task check' to verify."

  setup-podman:
    desc: Install Podman and podman-compose
    cmds:
      - sudo apt-get update
      - sudo apt-get install -y podman podman-compose

  check:
    desc: Check environment (GPU, Podman, etc.)
    cmds:
      - echo "=== Checking Environment ==="
      - echo ""
      - echo "[Podman]"
      - podman --version || echo "NOT INSTALLED"
      - echo ""
      - echo "[NVIDIA Driver]"
      - nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader || echo "NOT AVAILABLE"
      - echo ""
      - echo "[NVIDIA Container Toolkit]"
      - nvidia-ctk --version || echo "NOT INSTALLED"
      - echo ""
      - echo "[CDI Devices]"
      - nvidia-ctk cdi list 2>/dev/null || echo "CDI not configured"

  check-gpu:
    desc: Test GPU access in container
    cmds:
      - podman run --rm --device nvidia.com/gpu=all nvidia/cuda:11.8.0-base-ubuntu22.04 nvidia-smi

  # ===========================================
  # Build Tasks
  # ===========================================

  build:
    desc: Build the container image
    cmds:
      - echo "Building {{.IMAGE_NAME}}:{{.IMAGE_TAG}}..."
      - podman build -t {{.IMAGE_NAME}}:{{.IMAGE_TAG}} -f Containerfile .
      - echo "Build complete!"

  build-nocache:
    desc: Build the container image without cache
    cmds:
      - podman build --no-cache -t {{.IMAGE_NAME}}:{{.IMAGE_TAG}} -f Containerfile .

  # ===========================================
  # Run Tasks
  # ===========================================

  convert:
    desc: "Convert PDFs without OCR (use INPUT_DIR and OUTPUT_DIR vars)"
    cmds:
      - 'echo "Input: {{.INPUT_DIR}}"'
      - 'echo "Output: {{.OUTPUT_DIR}}"'
      - mkdir -p {{.OUTPUT_DIR}}
      - |
        podman run --rm \
          --device nvidia.com/gpu=all \
          --security-opt=label=disable \
          -v "$(realpath {{.INPUT_DIR}}):/data/input:ro" \
          -v "$(realpath {{.OUTPUT_DIR}}):/data/output:rw" \
          -e NVIDIA_VISIBLE_DEVICES=all \
          {{.IMAGE_NAME}}:{{.IMAGE_TAG}} \
          ConvertPdf /data/input /dst:/data/output /ocr:no

  convert-ocr:
    desc: Convert PDFs with Japanese OCR enabled
    cmds:
      - 'echo "Input: {{.INPUT_DIR}}"'
      - 'echo "Output: {{.OUTPUT_DIR}}"'
      - 'echo "OCR: enabled"'
      - mkdir -p {{.OUTPUT_DIR}}
      - |
        podman run --rm \
          --device nvidia.com/gpu=all \
          --security-opt=label=disable \
          -v "$(realpath {{.INPUT_DIR}}):/data/input:ro" \
          -v "$(realpath {{.OUTPUT_DIR}}):/data/output:rw" \
          -e NVIDIA_VISIBLE_DEVICES=all \
          {{.IMAGE_NAME}}:{{.IMAGE_TAG}} \
          ConvertPdf /data/input /dst:/data/output /ocr:yes

  shell:
    desc: Start interactive shell in container
    cmds:
      - |
        podman run --rm -it \
          --device nvidia.com/gpu=all \
          --security-opt=label=disable \
          -v "$(pwd)/examples/00_before:/data/input:ro" \
          -v "$(pwd)/examples/02_after:/data/output:rw" \
          -e NVIDIA_VISIBLE_DEVICES=all \
          --entrypoint /bin/bash \
          {{.IMAGE_NAME}}:{{.IMAGE_TAG}}

  compose-up:
    desc: Run with podman-compose
    cmds:
      - podman-compose up

  # ===========================================
  # Development Tasks
  # ===========================================

  dev-build:
    desc: Build .NET project locally (requires dotnet SDK)
    cmds:
      - dotnet build SuperBookToolsApp/SuperBookToolsApp.csproj -c Release

  dev-run:
    desc: Run .NET project locally
    dir: SuperBookToolsApp
    cmds:
      - dotnet run --project SuperBookToolsApp.csproj

  # ===========================================
  # Utility Tasks
  # ===========================================

  clean:
    desc: Remove built container image
    cmds:
      - podman rmi {{.IMAGE_NAME}}:{{.IMAGE_TAG}} || true

  clean-all:
    desc: Remove all related containers and images
    cmds:
      - podman rm -f $(podman ps -aq --filter ancestor={{.IMAGE_NAME}}:{{.IMAGE_TAG}}) 2>/dev/null || true
      - podman rmi {{.IMAGE_NAME}}:{{.IMAGE_TAG}} || true
      - podman volume prune -f

  logs:
    desc: Show container logs
    cmds:
      - podman logs superbook-pdf-converter

  prune:
    desc: Clean up unused Podman resources
    cmds:
      - podman system prune -f
